/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'created_at' : Time,
  'author' : IDL.Text,
  'featured_image' : IDL.Opt(IDL.Text),
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'post_id' : IDL.Nat,
  'text' : IDL.Text,
  'created_at' : Time,
  'author' : IDL.Text,
});

export const idlService = IDL.Service({
  'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getCommentsForPost' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [Post], ['query']),
  'updatePost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'created_at' : Time,
    'author' : IDL.Text,
    'featured_image' : IDL.Opt(IDL.Text),
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'post_id' : IDL.Nat,
    'text' : IDL.Text,
    'created_at' : Time,
    'author' : IDL.Text,
  });
  
  return IDL.Service({
    'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getCommentsForPost' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [Post], ['query']),
    'updatePost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };